#!/bin/sh
# Copyright (C) 2025 RZ781
#
# This file is part of libcitrus.
#
# libcitrus is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation, either version 2.1 of the License, or
# (at your option) any later version.
#
# libcitrus is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this program.  If not, see
# <https://www.gnu.org/licenses/>.

# format code
VERSION_CONTROL=none indent -linux src/* include/* tests/*

./build

# verify no symbols from libc are used
undefined_symbols="$(nm -u libcitrus.so | grep -v __stack_chk)"
if [ -n "$undefined_symbols" ] ; then
	echo "undefined symbols:"
	echo "$undefined_symbols"
fi

# run tests
gcc -Wall -Wextra -Wpedantic -Iinclude -Itests -g tests/*.c -Wl,-rpath='${ORIGIN}' -L. -lcitrus -o test || exit $?
./test || exit $?
rm test
